name: Error Reference Publisher
on:
  push:
    branches:
      - 'err-ref-ci'

jobs:
  error-ref:
    name: Error codes utility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}

      - name: Update docs
        uses: actions/checkout@v2
        with:
          repository: 'DelusionalOptimist/meshery'
          token: ${{ secrets.PAT }}
          path: 'meshery'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_message: "[Docs] update meshery server error reference"
          repository: './meshery'

          #      - run: |
          #          go run github.com/layer5io/meshkit/cmd/errorutil -d . update --skip-dirs meshery
          #          echo '{ "errors_export": '$(cat errorutil_errors_export.json)' }' | jq > ./meshery/docs/_data/errorref/istio_errors_export.json
          #
          #          cd ./meshery
          #          git config user.name l5io
          #          git config user.email ci@layer5.io
          #          git add ./docs/_data/errorref/istio_errors_export.json
          #          git commit -m "[Docs] meshery-istio error codes reference"
          #          git push origin master
