name: Meshery-istio OAM
on:
  push:
    branches:
      - 'gen-oam'

jobs:
  oam:
    name: Generate and push OAM definitions
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release tag
        id: glrt
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: istio/istio
          excludes: prerelease, draft

      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          #token: ${{ secrets.GH_ACCESS_TOKEN }}
          token: ${{ secrets.PAT }}

      - name: Get CURRENT_ISTIO_VERSION from .env
        run: |
          cat .github/.env >> $GITHUB_ENV

      - name: Get Istio manifests
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        run: |
          eval $(curl -L https://istio.io/downloadIstio | sh - | grep "PATH")
          istioctl manifest generate > ~/istio.yml

      - name: Bulild jsonschema util
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          nvm install v14.15.3
          nvm install-latest-npm
          git clone https://github.com/layer5io/kubeopenapi-jsonschema util
          cd util
          npm i; npm i nexe -g
          make linux

      - name: Generate Workload definitions
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        env:
          ISTIO_VERSION: ${{ steps.glrt.outputs.release }}
        run: |
          cd util
          template='{"apiVersion":"core.oam.dev/v1alpha1","kind":"WorkloadDefinition","metadata":{"name":""},"spec":{"definitionRef":{"name":""}}}'

          crds=$(./kubeopenapi-jsonschema --location ~/istio.yml -t yaml --filter '$[?(@.kind=="CustomResourceDefinition")]' -o json --o-filter '$..["spec"]["names"]["kind"]' | jq '.[]')

          for t in ${crds[@]}; do

            name=`echo $t  | tr -d '"' | tr '[:upper:]' '[:lower:]'`
            definitionRef=$name.meshery.layer5.io

            ./kubeopenapi-jsonschema --location ~/istio.yml -t yaml --filter '$[?(@.kind=="CustomResourceDefinition" && @.spec.names.kind=='$t')]..openAPIV3Schema.properties.spec' --o-filter "$[]" -o json | jq '.[] | .version = "'$ISTIO_VERSION'" | .title = '$t'' > ../templates/oam/workloads-$ISTIO_VERSION/$(printf %s.meshery.layer5io.schema.json $name)

            echo $template | jq ' ."metadata"."name" = '$t' | ."spec"."definitionRef"."name"="'$definitionRef'"' > ../templates/oam/workloads-$ISTIO_VERSION/$(printf %s_definition.json $name)

          done

      - name: Cleanup
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        run: |
          rm -rf util istio-*

      - name: Update Istio version env var
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        run: |
          echo "CURRENT_ISTIO_VERSION=${{ steps.glrt.outputs.release }}" > .github/.env

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./templates ./.github
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: "[Docs] Error Code Reference: update Meshery server and mehseryctl error codes"

      - name: Push Templates
        if: ${{ steps.glrt.outputs.release > env.CURRENT_ISTIO_VERSION }}
        run: |
          git config user.name "l5io"
          git config user.email "ci@layer5.io"
          git add ./templates ./.github
          git commit -m "push latest OAM definitions and schemas"
          git push origin gen-oam
